// Automatically generated by the res2go IDE plug-in.
package main

import (
	"github.com/moonfdd/ffmpeg-go-examples/examples/govclvideo/govclui/code/vclpkgui"
	_ "github.com/ying32/govcl/pkgs/winappres"
	"github.com/ying32/govcl/vcl"
)

func main() {
	vcl.Application.SetScaled(true)
	vcl.Application.SetTitle("project1")
	vcl.Application.Initialize()
	vcl.Application.SetMainFormOnTaskBar(true)
	vcl.Application.CreateForm(&vclpkgui.Form1)
	vcl.Application.Run()
}
