// Automatically generated by the res2go IDE plug-in, do not edit.
package vclpkgui

import (
    "github.com/ying32/govcl/vcl"
    _ "embed"
)

type TForm1 struct {
    *vcl.TForm
    Panel1   *vcl.TPanel
    Button1  *vcl.TButton
    Button2  *vcl.TButton
    Label1   *vcl.TLabel
    Button3  *vcl.TButton
    Panel2   *vcl.TPanel
    Button4  *vcl.TButton
    Button5  *vcl.TButton
    Label2   *vcl.TLabel
    Panel3   *vcl.TPanel
    Button6  *vcl.TButton
    Button7  *vcl.TButton
    Edit1    *vcl.TEdit
    Label3   *vcl.TLabel
    Panel4   *vcl.TPanel
    Button8  *vcl.TButton
    Button9  *vcl.TButton
    Label4   *vcl.TLabel
    Edit2    *vcl.TEdit
    Panel5   *vcl.TPanel
    Button10 *vcl.TButton
    Button11 *vcl.TButton
    Label5   *vcl.TLabel
    Edit3    *vcl.TEdit
    Panel6   *vcl.TPanel
    Edit4    *vcl.TEdit
    Button12 *vcl.TButton
    Button13 *vcl.TButton
    Button14 *vcl.TButton
    Button15 *vcl.TButton

    //::private::
    TForm1Fields
}

var Form1 *TForm1




// vcl.Application.CreateForm(&Form1)

func NewForm1(owner vcl.IComponent) (root *TForm1)  {
    vcl.CreateResForm(owner, &root)
    return
}

//go:embed resources/unit1.gfm
var form1Bytes []byte

// Register Form Resources
var _ = vcl.RegisterFormResource(Form1, &form1Bytes)
